<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AllPagesContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * This seeder contains ALL content for ALL pages in the website
     * organized by page/section for easy management.
     */
    public function run(): void
    {
        $settings = [
            // ========================================
            // LIVE-IN CARE PAGE
            // ========================================
            [
                'key' => 'liveincare_hero_title',
                'value_en' => 'Trusted Nurse-led 24-Hour Live-In Care',
                'value_pl' => 'Zaufana opieka 24-godzinna kierowana przez pielęgniarki',
                'value_nl' => 'Vertrouwde door verpleegkundigen geleide 24-uurs thuiszorg',
                'type' => 'text',
                'group' => 'liveincare_hero',
            ],
            [
                'key' => 'liveincare_hero_subtitle',
                'value_en' => 'Providing dedicated, compassionate care in the comfort of your own home',
                'value_pl' => 'Zapewniamy dedykowaną, współczującą opiekę w komforcie Twojego własnego domu',
                'value_nl' => 'Toegewijde, compassievolle zorg in het comfort van uw eigen huis',
                'type' => 'text',
                'group' => 'liveincare_hero',
            ],
            [
                'key' => 'liveincare_hero_cta',
                'value_en' => 'Call Us:',
                'value_pl' => 'Zadzwoń do nas:',
                'value_nl' => 'Bel ons:',
                'type' => 'text',
                'group' => 'liveincare_hero',
            ],
            [
                'key' => 'liveincare_what_title',
                'value_en' => 'What is Live-in Care?',
                'value_pl' => 'Czym jest opieka domowa?',
                'value_nl' => 'Wat is thuiszorg?',
                'type' => 'text',
                'group' => 'liveincare_content',
            ],
            [
                'key' => 'liveincare_what_description_1',
                'value_en' => 'Live-in care involves a dedicated care professional residing with you in your home, providing 24/7 support and companionship. This comprehensive care approach helps reduce risks like falls and hospital admissions while maintaining your independence and comfort in familiar surroundings.',
                'value_pl' => 'Opieka domowa polega na tym, że dedykowany opiekun mieszka z Tobą w Twoim domu, zapewniając całodobowe wsparcie i towarzystwo. To kompleksowe podejście do opieki pomaga zmniejszyć ryzyko upadków i hospitalizacji, jednocześnie zachowując Twoją niezależność i komfort w znanym otoczeniu.',
                'value_nl' => 'Thuiszorg betekent dat een toegewijde zorgprofessional bij u thuis woont en 24/7 ondersteuning en gezelschap biedt. Deze uitgebreide zorgaanpak helpt risico\'s zoals vallen en ziekenhuisopnames te verminderen, terwijl u uw onafhankelijkheid en comfort in vertrouwde omgeving behoudt.',
                'type' => 'textarea',
                'group' => 'liveincare_content',
            ],
            [
                'key' => 'liveincare_what_description_2',
                'value_en' => 'Our nurse-led service ensures the highest quality of care, tailored to your individual needs and preferences.',
                'value_pl' => 'Nasza usługa kierowana przez pielęgniarki zapewnia najwyższą jakość opieki, dostosowaną do Twoich indywidualnych potrzeb i preferencji.',
                'value_nl' => 'Onze door verpleegkundigen geleide dienst garandeert de hoogste kwaliteit zorg, afgestemd op uw individuele behoeften en voorkeuren.',
                'type' => 'textarea',
                'group' => 'liveincare_content',
            ],
            [
                'key' => 'liveincare_who_title',
                'value_en' => 'Who We Care For',
                'value_pl' => 'Dla kogo się opiekujemy',
                'value_nl' => 'Voor wie zorgen wij',
                'type' => 'text',
                'group' => 'liveincare_content',
            ],
            [
                'key' => 'liveincare_who_description',
                'value_en' => 'We provide specialized care for elderly individuals and younger people with advanced needs, including:',
                'value_pl' => 'Zapewniamy specjalistyczną opiekę dla osób starszych i młodszych osób z zaawansowanymi potrzebami, w tym:',
                'value_nl' => 'Wij bieden gespecialiseerde zorg voor oudere personen en jongere mensen met gevorderde behoeften, waaronder:',
                'type' => 'textarea',
                'group' => 'liveincare_content',
            ],
            [
                'key' => 'liveincare_condition_spinal',
                'value_en' => 'Spinal Injuries',
                'value_pl' => 'Urazy kręgosłupa',
                'value_nl' => 'Ruggenmergletsel',
                'type' => 'text',
                'group' => 'liveincare_conditions',
            ],
            [
                'key' => 'liveincare_condition_ms',
                'value_en' => 'Multiple Sclerosis',
                'value_pl' => 'Stwardnienie rozsiane',
                'value_nl' => 'Multiple Sclerose',
                'type' => 'text',
                'group' => 'liveincare_conditions',
            ],
            [
                'key' => 'liveincare_condition_brain',
                'value_en' => 'Brain Injury',
                'value_pl' => 'Uraz mózgu',
                'value_nl' => 'Hersenletsel',
                'type' => 'text',
                'group' => 'liveincare_conditions',
            ],
            [
                'key' => 'liveincare_condition_cerebral',
                'value_en' => 'Cerebral Palsy',
                'value_pl' => 'Porażenie mózgowe',
                'value_nl' => 'Cerebrale parese',
                'type' => 'text',
                'group' => 'liveincare_conditions',
            ],
            [
                'key' => 'liveincare_condition_frailty',
                'value_en' => 'Age-related Frailty',
                'value_pl' => 'Słabość związana z wiekiem',
                'value_nl' => 'Leeftijdsgerelateerde kwetsbaarheid',
                'type' => 'text',
                'group' => 'liveincare_conditions',
            ],
            [
                'key' => 'liveincare_condition_dementia',
                'value_en' => 'Dementia Care',
                'value_pl' => 'Opieka nad osobami z demencją',
                'value_nl' => 'Dementiezorg',
                'type' => 'text',
                'group' => 'liveincare_conditions',
            ],
            [
                'key' => 'liveincare_tasks_title',
                'value_en' => 'Live-in Carer Tasks',
                'value_pl' => 'Zadania opiekuna domowego',
                'value_nl' => 'Taken van de thuiszorger',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_tasks_description',
                'value_en' => 'Our dedicated carers provide comprehensive support with:',
                'value_pl' => 'Nasi dedykowani opiekunowie zapewniają kompleksowe wsparcie w zakresie:',
                'value_nl' => 'Onze toegewijde zorgverleners bieden uitgebreide ondersteuning bij:',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_personal',
                'value_en' => 'Personal Care',
                'value_pl' => 'Opieka osobista',
                'value_nl' => 'Persoonlijke verzorging',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_medication',
                'value_en' => 'Medication Management',
                'value_pl' => 'Zarządzanie lekami',
                'value_nl' => 'Medicatiebeheer',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_cleaning',
                'value_en' => 'Home Cleaning',
                'value_pl' => 'Sprzątanie domu',
                'value_nl' => 'Huishouding',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_meals',
                'value_en' => 'Meal Preparation',
                'value_pl' => 'Przygotowanie posiłków',
                'value_nl' => 'Maaltijdbereiding',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_errands',
                'value_en' => 'Errands & Shopping',
                'value_pl' => 'Sprawy i zakupy',
                'value_nl' => 'Boodschappen',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_trips',
                'value_en' => 'Trip Arrangements',
                'value_pl' => 'Organizacja wyjazdów',
                'value_nl' => 'Reisarrangementen',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_pets',
                'value_en' => 'Pet Care',
                'value_pl' => 'Opieka nad zwierzętami',
                'value_nl' => 'Huisdierenzorg',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_task_healthcare',
                'value_en' => 'Healthcare Tasks',
                'value_pl' => 'Zadania zdrowotne',
                'value_nl' => 'Gezondheidszorgtaken',
                'type' => 'text',
                'group' => 'liveincare_tasks',
            ],
            [
                'key' => 'liveincare_benefits_title',
                'value_en' => 'Benefits of Live-in Care',
                'value_pl' => 'Korzyści z opieki domowej',
                'value_nl' => 'Voordelen van thuiszorg',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_flexibility_title',
                'value_en' => 'Flexibility & Freedom',
                'value_pl' => 'Elastyczność i wolność',
                'value_nl' => 'Flexibiliteit & vrijheid',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_flexibility_desc',
                'value_en' => 'Maintain your independence and daily routines in the comfort of your own home',
                'value_pl' => 'Zachowaj swoją niezależność i codzienne rutyny w komforcie własnego domu',
                'value_nl' => 'Behoud uw onafhankelijkheid en dagelijkse routines in het comfort van uw eigen huis',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_familiar_title',
                'value_en' => 'Familiar Environment',
                'value_pl' => 'Znane otoczenie',
                'value_nl' => 'Vertrouwde omgeving',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_familiar_desc',
                'value_en' => 'Stay in your cherished home surrounded by memories and belongings',
                'value_pl' => 'Pozostań w swoim ukochanym domu otoczonym wspomnieniami i rzeczami',
                'value_nl' => 'Blijf in uw geliefde huis omgeven door herinneringen en bezittingen',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_personalized_title',
                'value_en' => 'Personalized Care',
                'value_pl' => 'Spersonalizowana opieka',
                'value_nl' => 'Gepersonaliseerde zorg',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_personalized_desc',
                'value_en' => 'Receive one-on-one attention tailored to your unique needs and preferences',
                'value_pl' => 'Otrzymaj indywidualną uwagę dostosowaną do Twoich unikalnych potrzeb i preferencji',
                'value_nl' => 'Ontvang individuele aandacht afgestemd op uw unieke behoeften en voorkeuren',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_consistent_title',
                'value_en' => 'Consistent Caregiver',
                'value_pl' => 'Stały opiekun',
                'value_nl' => 'Consistente zorgverlener',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_consistent_desc',
                'value_en' => 'Build meaningful relationships with your dedicated care professional',
                'value_pl' => 'Zbuduj znaczące relacje ze swoim dedykowanym profesjonalistą opiekuńczym',
                'value_nl' => 'Bouw betekenisvolle relaties op met uw toegewijde zorgprofessional',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_health_title',
                'value_en' => 'Improved Health',
                'value_pl' => 'Lepsze zdrowie',
                'value_nl' => 'Verbeterde gezondheid',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_health_desc',
                'value_en' => 'Better health outcomes through personalized, attentive care',
                'value_pl' => 'Lepsze wyniki zdrowotne dzięki spersonalizowanej, uważnej opiece',
                'value_nl' => 'Betere gezondheidsresultaten door gepersonaliseerde, aandachtige zorg',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_pets_title',
                'value_en' => 'Pet Care Support',
                'value_pl' => 'Wsparcie w opiece nad zwierzętami',
                'value_nl' => 'Huisdierenzorg ondersteuning',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_benefit_pets_desc',
                'value_en' => 'Keep your beloved pets with you while receiving proper care',
                'value_pl' => 'Zachowaj swoje ukochane zwierzęta przy sobie, otrzymując odpowiednią opiekę',
                'value_nl' => 'Houd uw geliefde huisdieren bij u terwijl u goede zorg ontvangt',
                'type' => 'text',
                'group' => 'liveincare_benefits',
            ],
            [
                'key' => 'liveincare_pricing_title',
                'value_en' => 'Transparent Pricing',
                'value_pl' => 'Przejrzyste ceny',
                'value_nl' => 'Transparante prijzen',
                'type' => 'text',
                'group' => 'liveincare_pricing',
            ],
            [
                'key' => 'liveincare_pricing_description',
                'value_en' => 'Fully managed live-in care starts from <span class="font-bold text-[#2563eb]">£1,350 per week</span>',
                'value_pl' => 'W pełni zarządzana opieka domowa zaczyna się od <span class="font-bold text-[#2563eb]">£1,350 tygodniowo</span>',
                'value_nl' => 'Volledig beheerde thuiszorg begint vanaf <span class="font-bold text-[#2563eb]">£1.350 per week</span>',
                'type' => 'text',
                'group' => 'liveincare_pricing',
            ],
            [
                'key' => 'liveincare_pricing_contact',
                'value_en' => 'Contact us for a free care assessment and personalized quote',
                'value_pl' => 'Skontaktuj się z nami, aby uzyskać bezpłatną ocenę opieki i spersonalizowaną wycenę',
                'value_nl' => 'Neem contact met ons op voor een gratis zorgbeoordeling en persoonlijke offerte',
                'type' => 'text',
                'group' => 'liveincare_pricing',
            ],
            [
                'key' => 'liveincare_cta_title',
                'value_en' => 'Ready to Learn More About Our Live-in Care Services?',
                'value_pl' => 'Gotowy dowiedzieć się więcej o naszych usługach opieki domowej?',
                'value_nl' => 'Klaar om meer te weten te komen over onze thuiszorgdiensten?',
                'type' => 'text',
                'group' => 'liveincare_cta',
            ],
            [
                'key' => 'liveincare_cta_subtitle',
                'value_en' => 'Contact us 24 hours a day for a free care assessment and quote',
                'value_pl' => 'Skontaktuj się z nami 24 godziny na dobę, aby uzyskać bezpłatną ocenę opieki i wycenę',
                'value_nl' => 'Neem 24 uur per dag contact met ons op voor een gratis zorgbeoordeling en offerte',
                'type' => 'text',
                'group' => 'liveincare_cta',
            ],
            [
                'key' => 'liveincare_cta_button_call',
                'value_en' => 'Call',
                'value_pl' => 'Zadzwoń',
                'value_nl' => 'Bel',
                'type' => 'text',
                'group' => 'liveincare_cta',
            ],
            [
                'key' => 'liveincare_cta_button_contact',
                'value_en' => 'Contact Us Online',
                'value_pl' => 'Skontaktuj się z nami online',
                'value_nl' => 'Neem online contact met ons op',
                'type' => 'text',
                'group' => 'liveincare_cta',
            ],

            // ========================================
            // CARE FUNDING PAGE
            // ========================================
            [
                'key' => 'carefunding_hero_title',
                'value_en' => 'Care Funding Options',
                'value_pl' => 'Opcje finansowania opieki',
                'value_nl' => 'Zorgfinancieringsopties',
                'type' => 'text',
                'group' => 'carefunding_hero',
            ],
            [
                'key' => 'carefunding_hero_subtitle',
                'value_en' => 'Understanding how to fund your care - we\'re here to help you navigate the options',
                'value_pl' => 'Zrozumienie, jak sfinansować swoją opiekę - jesteśmy tutaj, aby pomóc Ci poruszać się po opcjach',
                'value_nl' => 'Begrijpen hoe u uw zorg kunt financieren - wij helpen u graag bij het navigeren door de opties',
                'type' => 'text',
                'group' => 'carefunding_hero',
            ],
            [
                'key' => 'carefunding_intro_title',
                'value_en' => 'How to Fund Your Care',
                'value_pl' => 'Jak sfinansować swoją opiekę',
                'value_nl' => 'Hoe uw zorg te financieren',
                'type' => 'text',
                'group' => 'carefunding_intro',
            ],
            [
                'key' => 'carefunding_intro_desc1',
                'value_en' => 'Funding care can seem complex, but we\'re here to guide you through the various options available. Whether you\'re considering self-funding, local authority support, or NHS Continuing Healthcare, we\'ll help you understand what\'s available to you.',
                'value_pl' => 'Finansowanie opieki może wydawać się skomplikowane, ale jesteśmy tutaj, aby poprowadzić Cię przez różne dostępne opcje. Niezależnie od tego, czy rozważasz samodzielne finansowanie, wsparcie władz lokalnych czy NHS Continuing Healthcare, pomożemy Ci zrozumieć, co jest dla Ciebie dostępne.',
                'value_nl' => 'Het financieren van zorg kan complex lijken, maar wij zijn er om u door de verschillende beschikbare opties te leiden. Of u nu overweegt om zelf te betalen, steun van de lokale overheid of NHS Continuing Healthcare, wij helpen u begrijpen wat er voor u beschikbaar is.',
                'type' => 'textarea',
                'group' => 'carefunding_intro',
            ],
            [
                'key' => 'carefunding_intro_desc2',
                'value_en' => 'Our team can provide guidance on the most suitable funding routes based on your individual circumstances and care needs.',
                'value_pl' => 'Nasz zespół może udzielić wskazówek dotyczących najbardziej odpowiednich sposobów finansowania w oparciu o Twoje indywidualne okoliczności i potrzeby opiekuńcze.',
                'value_nl' => 'Ons team kan advies geven over de meest geschikte financieringsroutes op basis van uw individuele omstandigheden en zorgbehoeften.',
                'type' => 'textarea',
                'group' => 'carefunding_intro',
            ],
            [
                'key' => 'carefunding_options_title',
                'value_en' => 'Funding Options Available',
                'value_pl' => 'Dostępne opcje finansowania',
                'value_nl' => 'Beschikbare financieringsopties',
                'type' => 'text',
                'group' => 'carefunding_options',
            ],
            [
                'key' => 'carefunding_self_title',
                'value_en' => 'Self-Funding',
                'value_pl' => 'Samodzielne finansowanie',
                'value_nl' => 'Zelffinanciering',
                'type' => 'text',
                'group' => 'carefunding_self',
            ],
            [
                'key' => 'carefunding_self_desc1',
                'value_en' => 'Many people choose to pay for their own care privately. This gives you complete control over your care choices and the flexibility to arrange services that perfectly match your needs and preferences.',
                'value_pl' => 'Wiele osób decyduje się na prywatne opłacanie własnej opieki. Daje to pełną kontrolę nad wyborami opieki i elastyczność w aranżowaniu usług, które idealnie pasują do Twoich potrzeb i preferencji.',
                'value_nl' => 'Veel mensen kiezen ervoor om privé voor hun eigen zorg te betalen. Dit geeft u volledige controle over uw zorgkeuzes en de flexibiliteit om diensten te regelen die perfect bij uw behoeften en voorkeuren passen.',
                'type' => 'textarea',
                'group' => 'carefunding_self',
            ],
            [
                'key' => 'carefunding_self_desc2',
                'value_en' => 'If you have assets over £23,250, you\'ll likely need to self-fund your care initially. We offer transparent pricing and can provide detailed cost breakdowns to help you plan.',
                'value_pl' => 'Jeśli posiadasz aktywa powyżej £23,250, prawdopodobnie będziesz musiał początkowo samodzielnie finansować swoją opiekę. Oferujemy przejrzyste ceny i możemy dostarczyć szczegółowe zestawienia kosztów, aby pomóc Ci w planowaniu.',
                'value_nl' => 'Als u bezittingen heeft van meer dan £23.250, moet u waarschijnlijk aanvankelijk zelf voor uw zorg betalen. Wij bieden transparante prijzen en kunnen gedetailleerde kostenspecificaties verstrekken om u te helpen bij het plannen.',
                'type' => 'textarea',
                'group' => 'carefunding_self',
            ],
            [
                'key' => 'carefunding_local_title',
                'value_en' => 'Local Authority Support',
                'value_pl' => 'Wsparcie władz lokalnych',
                'value_nl' => 'Ondersteuning van de lokale overheid',
                'type' => 'text',
                'group' => 'carefunding_local',
            ],
            [
                'key' => 'carefunding_local_desc1',
                'value_en' => 'If your assets are below £23,250, you may be eligible for financial support from your local council. The amount of support depends on your financial assessment and care needs.',
                'value_pl' => 'Jeśli Twoje aktywa są poniżej £23,250, możesz kwalifikować się do wsparcia finansowego od lokalnej rady. Wysokość wsparcia zależy od Twojej oceny finansowej i potrzeb opiekuńczych.',
                'value_nl' => 'Als uw bezittingen minder dan £23.250 bedragen, komt u mogelijk in aanmerking voor financiële ondersteuning van uw gemeente. De hoeveelheid ondersteuning hangt af van uw financiële beoordeling en zorgbehoeften.',
                'type' => 'textarea',
                'group' => 'carefunding_local',
            ],
            [
                'key' => 'carefunding_local_desc2',
                'value_en' => 'We can guide you through the assessment process and work with your local authority to arrange suitable care packages.',
                'value_pl' => 'Możemy poprowadzić Cię przez proces oceny i współpracować z władzami lokalnymi, aby zorganizować odpowiednie pakiety opieki.',
                'value_nl' => 'Wij kunnen u door het beoordelingsproces leiden en samenwerken met uw gemeente om geschikte zorgpakketten te regelen.',
                'type' => 'textarea',
                'group' => 'carefunding_local',
            ],
            [
                'key' => 'carefunding_nhs_title',
                'value_en' => 'NHS Continuing Healthcare',
                'value_pl' => 'Ciągła opieka zdrowotna NHS',
                'value_nl' => 'NHS Continue zorg',
                'type' => 'text',
                'group' => 'carefunding_nhs',
            ],
            [
                'key' => 'carefunding_nhs_desc1',
                'value_en' => 'If you have complex medical needs, you may qualify for NHS Continuing Healthcare (CHC). This is a package of care arranged and funded solely by the NHS for individuals who have ongoing healthcare needs.',
                'value_pl' => 'Jeśli masz złożone potrzeby medyczne, możesz kwalifikować się do NHS Continuing Healthcare (CHC). Jest to pakiet opieki organizowany i finansowany wyłącznie przez NHS dla osób z bieżącymi potrzebami zdrowotnymi.',
                'value_nl' => 'Als u complexe medische behoeften heeft, komt u mogelijk in aanmerking voor NHS Continuing Healthcare (CHC). Dit is een zorgpakket dat uitsluitend door de NHS wordt geregeld en gefinancierd voor personen met doorlopende zorgbehoeften.',
                'type' => 'textarea',
                'group' => 'carefunding_nhs',
            ],
            [
                'key' => 'carefunding_nhs_desc2',
                'value_en' => 'We can support you through the CHC assessment process and provide the necessary documentation to support your application.',
                'value_pl' => 'Możemy wesprzeć Cię w procesie oceny CHC i dostarczyć niezbędną dokumentację wspierającą Twoją aplikację.',
                'value_nl' => 'Wij kunnen u ondersteunen bij het CHC-beoordelingsproces en de nodige documentatie verstrekken om uw aanvraag te ondersteunen.',
                'type' => 'textarea',
                'group' => 'carefunding_nhs',
            ],
            [
                'key' => 'carefunding_other_title',
                'value_en' => 'Other Funding Sources',
                'value_pl' => 'Inne źródła finansowania',
                'value_nl' => 'Andere financieringsbronnen',
                'type' => 'text',
                'group' => 'carefunding_other',
            ],
            [
                'key' => 'carefunding_other_intro',
                'value_en' => 'Additional funding options may include:',
                'value_pl' => 'Dodatkowe opcje finansowania mogą obejmować:',
                'value_nl' => 'Aanvullende financieringsopties kunnen zijn:',
                'type' => 'text',
                'group' => 'carefunding_other',
            ],
            [
                'key' => 'carefunding_other_deferred',
                'value_en' => 'Deferred payment agreements',
                'value_pl' => 'Umowy o odroczonych płatnościach',
                'value_nl' => 'Uitgestelde betalingsregelingen',
                'type' => 'text',
                'group' => 'carefunding_other',
            ],
            [
                'key' => 'carefunding_other_veterans',
                'value_en' => 'Veterans\' benefits and support',
                'value_pl' => 'Świadczenia i wsparcie dla weteranów',
                'value_nl' => 'Veteranenuitkeringen en ondersteuning',
                'type' => 'text',
                'group' => 'carefunding_other',
            ],
            [
                'key' => 'carefunding_other_attendance',
                'value_en' => 'Attendance Allowance or Personal Independence Payment',
                'value_pl' => 'Zasiłek opiekuńczy lub Płatność za Osobistą Niezależność',
                'value_nl' => 'Aanwezigheidstoelage of Persoonlijke Onafhankelijkheidsbetaling',
                'type' => 'text',
                'group' => 'carefunding_other',
            ],
            [
                'key' => 'carefunding_other_charity',
                'value_en' => 'Charity grants and support funds',
                'value_pl' => 'Dotacje charytatywne i fundusze wsparcia',
                'value_nl' => 'Liefdadigheidssubsidies en ondersteunende fondsen',
                'type' => 'text',
                'group' => 'carefunding_other',
            ],
            [
                'key' => 'carefunding_help_title',
                'value_en' => 'How We Can Help',
                'value_pl' => 'Jak możemy pomóc',
                'value_nl' => 'Hoe wij kunnen helpen',
                'type' => 'text',
                'group' => 'carefunding_help',
            ],
            [
                'key' => 'carefunding_help_intro',
                'value_en' => 'Our experienced team understands that navigating care funding can be overwhelming. We\'re here to support you every step of the way:',
                'value_pl' => 'Nasz doświadczony zespół rozumie, że poruszanie się po finansowaniu opieki może być przytłaczające. Jesteśmy tutaj, aby wesprzeć Cię na każdym kroku:',
                'value_nl' => 'Ons ervaren team begrijpt dat het navigeren door zorgfinanciering overweldigend kan zijn. Wij zijn er om u bij elke stap te ondersteunen:',
                'type' => 'textarea',
                'group' => 'carefunding_help',
            ],
            [
                'key' => 'carefunding_help_pricing',
                'value_en' => 'Provide clear, transparent pricing information',
                'value_pl' => 'Zapewnić jasne, przejrzyste informacje cenowe',
                'value_nl' => 'Duidelijke, transparante prijsinformatie verstrekken',
                'type' => 'text',
                'group' => 'carefunding_help',
            ],
            [
                'key' => 'carefunding_help_assessment',
                'value_en' => 'Guide you through financial assessments',
                'value_pl' => 'Poprowadzić Cię przez oceny finansowe',
                'value_nl' => 'U begeleiden door financiële beoordelingen',
                'type' => 'text',
                'group' => 'carefunding_help',
            ],
            [
                'key' => 'carefunding_help_nhs',
                'value_en' => 'Help with NHS Continuing Healthcare applications',
                'value_pl' => 'Pomóc z aplikacjami NHS Continuing Healthcare',
                'value_nl' => 'Hulp bij NHS Continue zorg aanvragen',
                'type' => 'text',
                'group' => 'carefunding_help',
            ],
            [
                'key' => 'carefunding_help_authority',
                'value_en' => 'Work with local authorities on your behalf',
                'value_pl' => 'Współpracować z władzami lokalnymi w Twoim imieniu',
                'value_nl' => 'Samenwerken met lokale overheden namens u',
                'type' => 'text',
                'group' => 'carefunding_help',
            ],
            [
                'key' => 'carefunding_help_benefits',
                'value_en' => 'Identify additional funding sources and benefits you may be entitled to',
                'value_pl' => 'Zidentyfikować dodatkowe źródła finansowania i świadczenia, do których możesz być uprawniony',
                'value_nl' => 'Aanvullende financieringsbronnen en uitkeringen identificeren waar u recht op heeft',
                'type' => 'text',
                'group' => 'carefunding_help',
            ],
            [
                'key' => 'carefunding_cta_title',
                'value_en' => 'Need Help Understanding Your Funding Options?',
                'value_pl' => 'Potrzebujesz pomocy w zrozumieniu opcji finansowania?',
                'value_nl' => 'Hulp nodig bij het begrijpen van uw financieringsopties?',
                'type' => 'text',
                'group' => 'carefunding_cta',
            ],
            [
                'key' => 'carefunding_cta_subtitle',
                'value_en' => 'Contact us for a free consultation to discuss your care funding options',
                'value_pl' => 'Skontaktuj się z nami, aby uzyskać bezpłatną konsultację w celu omówienia opcji finansowania opieki',
                'value_nl' => 'Neem contact met ons op voor een gratis consultatie om uw zorgfinancieringsopties te bespreken',
                'type' => 'text',
                'group' => 'carefunding_cta',
            ],

            // ========================================
            // CAREERS PAGE
            // ========================================
            [
                'key' => 'careers_hero_title',
                'value_en' => 'Apply for Live-In Care Jobs',
                'value_pl' => 'Aplikuj na pracę jako opiekun domowy',
                'value_nl' => 'Solliciteer voor thuiszorgbanen',
                'type' => 'text',
                'group' => 'careers_hero',
            ],
            [
                'key' => 'careers_hero_subtitle',
                'value_en' => 'Make a positive difference in people\'s lives with a rewarding career in care',
                'value_pl' => 'Zrób pozytywną różnicę w życiu ludzi dzięki satysfakcjonującej karierze w opiece',
                'value_nl' => 'Maak een positief verschil in het leven van mensen met een lonende carrière in de zorg',
                'type' => 'text',
                'group' => 'careers_hero',
            ],
            [
                'key' => 'careers_hero_button',
                'value_en' => 'Apply Now',
                'value_pl' => 'Aplikuj teraz',
                'value_nl' => 'Solliciteer nu',
                'type' => 'text',
                'group' => 'careers_hero',
            ],
            [
                'key' => 'careers_benefits_title',
                'value_en' => 'Job Benefits',
                'value_pl' => 'Korzyści z pracy',
                'value_nl' => 'Arbeidsvoordelen',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_financial_title',
                'value_en' => 'Financial Benefits',
                'value_pl' => 'Korzyści finansowe',
                'value_nl' => 'Financiële voordelen',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_pay_range',
                'value_en' => '£750-£950 per week',
                'value_pl' => '£750-£950 tygodniowo',
                'value_nl' => '£750-£950 per week',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_pay_rates',
                'value_en' => 'Market-leading pay rates',
                'value_pl' => 'Wiodące na rynku stawki',
                'value_nl' => 'Marktleidende salarissen',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_pension',
                'value_en' => 'Employer pension (3% contribution)',
                'value_pl' => 'Emerytura pracodawcy (3% wkładu)',
                'value_nl' => 'Werkgeverspensioen (3% bijdrage)',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_bank_holidays',
                'value_en' => 'Up to double pay for bank holidays',
                'value_pl' => 'Do podwójnej płacy za święta bankowe',
                'value_nl' => 'Tot dubbel loon voor feestdagen',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_referral',
                'value_en' => 'Refer-a-Friend bonus up to £1000',
                'value_pl' => 'Bonus za polecenie znajomego do £1000',
                'value_nl' => 'Verwijs-een-vriend bonus tot £1000',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_additional_title',
                'value_en' => 'Additional Benefits',
                'value_pl' => 'Dodatkowe korzyści',
                'value_nl' => 'Aanvullende voordelen',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_annual_leave',
                'value_en' => 'Paid annual leave (28-34 days)',
                'value_pl' => 'Płatny urlop roczny (28-34 dni)',
                'value_nl' => 'Betaald jaarlijks verlof (28-34 dagen)',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_healthcare',
                'value_en' => 'BUPA Healthcare cash plan',
                'value_pl' => 'Plan pieniężny BUPA Healthcare',
                'value_nl' => 'BUPA Healthcare geldplan',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_dbs',
                'value_en' => 'Free DBS check',
                'value_pl' => 'Bezpłatne sprawdzenie DBS',
                'value_nl' => 'Gratis DBS-controle',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_support',
                'value_en' => '24/7 support from our team',
                'value_pl' => 'Wsparcie 24/7 od naszego zespołu',
                'value_nl' => '24/7 ondersteuning van ons team',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_travel',
                'value_en' => 'Travel expenses paid',
                'value_pl' => 'Opłacone koszty podróży',
                'value_nl' => 'Reiskosten betaald',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_eap',
                'value_en' => 'Employee Assistance Programme',
                'value_pl' => 'Program Wsparcia Pracowników',
                'value_nl' => 'Werknemersondersteuningsprogramma',
                'type' => 'text',
                'group' => 'careers_benefits',
            ],
            [
                'key' => 'careers_responsibilities_title',
                'value_en' => 'Job Responsibilities',
                'value_pl' => 'Obowiązki zawodowe',
                'value_nl' => 'Functieverantwoordelijkheden',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_responsibilities_intro',
                'value_en' => 'As a live-in carer, you\'ll provide compassionate, personalized care including:',
                'value_pl' => 'Jako opiekun domowy zapewnisz współczującą, spersonalizowaną opiekę, w tym:',
                'value_nl' => 'Als thuiszorger biedt u compassievolle, gepersonaliseerde zorg, waaronder:',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_resp_personal',
                'value_en' => 'Personal care',
                'value_pl' => 'Opieka osobista',
                'value_nl' => 'Persoonlijke verzorging',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_resp_medication',
                'value_en' => 'Medication management',
                'value_pl' => 'Zarządzanie lekami',
                'value_nl' => 'Medicatiebeheer',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_resp_maintenance',
                'value_en' => 'Home maintenance',
                'value_pl' => 'Utrzymanie domu',
                'value_nl' => 'Huisonderhoud',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_resp_meals',
                'value_en' => 'Meal preparation',
                'value_pl' => 'Przygotowanie posiłków',
                'value_nl' => 'Maaltijdbereiding',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_resp_errands',
                'value_en' => 'Errands & shopping',
                'value_pl' => 'Sprawy i zakupy',
                'value_nl' => 'Boodschappen',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_resp_companion',
                'value_en' => 'Companion support',
                'value_pl' => 'Wsparcie towarzysza',
                'value_nl' => 'Gezelschapsondersteuning',
                'type' => 'text',
                'group' => 'careers_responsibilities',
            ],
            [
                'key' => 'careers_training_title',
                'value_en' => 'Comprehensive Training',
                'value_pl' => 'Kompleksowe szkolenie',
                'value_nl' => 'Uitgebreide training',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_training_intro',
                'value_en' => 'We provide full induction and ongoing training to ensure you\'re confident and well-prepared for your role:',
                'value_pl' => 'Zapewniamy pełne wprowadzenie i ciągłe szkolenia, aby zapewnić Ci pewność siebie i dobre przygotowanie do roli:',
                'value_nl' => 'Wij bieden volledige introductie en doorlopende training om ervoor te zorgen dat u zelfverzekerd en goed voorbereid bent op uw rol:',
                'type' => 'textarea',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_role_title',
                'value_en' => 'Role Understanding',
                'value_pl' => 'Zrozumienie roli',
                'value_nl' => 'Rolbegrip',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_role_desc',
                'value_en' => 'Complete overview of your responsibilities',
                'value_pl' => 'Pełny przegląd Twoich obowiązków',
                'value_nl' => 'Volledig overzicht van uw verantwoordelijkheden',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_medication_title',
                'value_en' => 'Medication Management',
                'value_pl' => 'Zarządzanie lekami',
                'value_nl' => 'Medicatiebeheer',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_medication_desc',
                'value_en' => 'Safe administration and record-keeping',
                'value_pl' => 'Bezpieczne podawanie i prowadzenie dokumentacji',
                'value_nl' => 'Veilige toediening en administratie',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_safety_title',
                'value_en' => 'Health & Safety',
                'value_pl' => 'Zdrowie i bezpieczeństwo',
                'value_nl' => 'Gezondheid & veiligheid',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_safety_desc',
                'value_en' => 'Essential safety protocols and procedures',
                'value_pl' => 'Niezbędne protokoły i procedury bezpieczeństwa',
                'value_nl' => 'Essentiële veiligheidsprotocollen en procedures',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_firstaid_title',
                'value_en' => 'First Aid',
                'value_pl' => 'Pierwsza pomoc',
                'value_nl' => 'Eerste hulp',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_firstaid_desc',
                'value_en' => 'Emergency response and first aid skills',
                'value_pl' => 'Reagowanie w nagłych wypadkach i umiejętności pierwszej pomocy',
                'value_nl' => 'Noodrespons en eerste hulp vaardigheden',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_handling_title',
                'value_en' => 'Manual Handling',
                'value_pl' => 'Obsługa ręczna',
                'value_nl' => 'Handmatig hanteren',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_handling_desc',
                'value_en' => 'Safe moving and handling techniques',
                'value_pl' => 'Bezpieczne techniki przenoszenia i obsługi',
                'value_nl' => 'Veilige verplaatsings- en hanteringstechnieken',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_infection_title',
                'value_en' => 'Infection Control',
                'value_pl' => 'Kontrola infekcji',
                'value_nl' => 'Infectiecontrole',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_train_infection_desc',
                'value_en' => 'Prevention and control measures',
                'value_pl' => 'Środki zapobiegawcze i kontrolne',
                'value_nl' => 'Preventie- en controlemaatregelen',
                'type' => 'text',
                'group' => 'careers_training',
            ],
            [
                'key' => 'careers_process_title',
                'value_en' => '6-Step Application Process',
                'value_pl' => '6-etapowy proces aplikacji',
                'value_nl' => '6-staps sollicitatieprocedure',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step1_title',
                'value_en' => 'Initial Contact',
                'value_pl' => 'Wstępny kontakt',
                'value_nl' => 'Eerste contact',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step1_desc',
                'value_en' => 'Submit your online application or call us',
                'value_pl' => 'Wyślij aplikację online lub zadzwoń do nas',
                'value_nl' => 'Dien uw online sollicitatie in of bel ons',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step2_title',
                'value_en' => 'Team Follow-up',
                'value_pl' => 'Kontakt zespołu',
                'value_nl' => 'Team follow-up',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step2_desc',
                'value_en' => 'We\'ll contact you within 24 hours',
                'value_pl' => 'Skontaktujemy się z Tobą w ciągu 24 godzin',
                'value_nl' => 'Wij nemen binnen 24 uur contact met u op',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step3_title',
                'value_en' => 'Online Interview',
                'value_pl' => 'Rozmowa online',
                'value_nl' => 'Online interview',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step3_desc',
                'value_en' => 'Convenient virtual interview process',
                'value_pl' => 'Wygodny proces wirtualnej rozmowy',
                'value_nl' => 'Handig virtueel interviewproces',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step4_title',
                'value_en' => 'Background Checks',
                'value_pl' => 'Sprawdzenie przeszłości',
                'value_nl' => 'Achtergrondcontroles',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step4_desc',
                'value_en' => 'DBS and reference verification',
                'value_pl' => 'Weryfikacja DBS i referencji',
                'value_nl' => 'DBS en referentieverificatie',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step5_title',
                'value_en' => 'In-Person Induction',
                'value_pl' => 'Wprowadzenie osobiste',
                'value_nl' => 'Persoonlijke introductie',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step5_desc',
                'value_en' => 'Two-day comprehensive training',
                'value_pl' => 'Dwudniowe kompleksowe szkolenie',
                'value_nl' => 'Tweedaagse uitgebreide training',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step6_title',
                'value_en' => 'First Placement',
                'value_pl' => 'Pierwsze zatrudnienie',
                'value_nl' => 'Eerste plaatsing',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_step6_desc',
                'value_en' => 'Start your rewarding care journey',
                'value_pl' => 'Rozpocznij swoją satysfakcjonującą podróż opiekuńczą',
                'value_nl' => 'Begin uw lonende zorgreis',
                'type' => 'text',
                'group' => 'careers_process',
            ],
            [
                'key' => 'careers_cta_title',
                'value_en' => 'Ready to Start Your Care Career?',
                'value_pl' => 'Gotowy rozpocząć karierę w opiece?',
                'value_nl' => 'Klaar om uw zorgcarrière te starten?',
                'type' => 'text',
                'group' => 'careers_cta',
            ],
            [
                'key' => 'careers_cta_subtitle',
                'value_en' => 'Join our dedicated team and make a real difference in people\'s lives',
                'value_pl' => 'Dołącz do naszego dedykowanego zespołu i zrób prawdziwą różnicę w życiu ludzi',
                'value_nl' => 'Sluit u aan bij ons toegewijde team en maak echt verschil in het leven van mensen',
                'type' => 'text',
                'group' => 'careers_cta',
            ],
            [
                'key' => 'careers_cta_button_apply',
                'value_en' => 'Apply Online Now',
                'value_pl' => 'Aplikuj online teraz',
                'value_nl' => 'Solliciteer nu online',
                'type' => 'text',
                'group' => 'careers_cta',
            ],

            // ========================================
            // CONTACT PAGE
            // ========================================
            [
                'key' => 'contact_hero_title',
                'value_en' => 'Get in Touch',
                'value_pl' => 'Skontaktuj się z nami',
                'value_nl' => 'Neem contact op',
                'type' => 'text',
                'group' => 'contact_hero',
            ],
            [
                'key' => 'contact_hero_subtitle',
                'value_en' => 'We\'re here to answer your questions and discuss how we can support you',
                'value_pl' => 'Jesteśmy tutaj, aby odpowiedzieć na Twoje pytania i omówić, jak możemy Cię wesprzeć',
                'value_nl' => 'Wij zijn er om uw vragen te beantwoorden en te bespreken hoe wij u kunnen ondersteunen',
                'type' => 'text',
                'group' => 'contact_hero',
            ],
            [
                'key' => 'contact_info_title',
                'value_en' => 'Contact Information',
                'value_pl' => 'Informacje kontaktowe',
                'value_nl' => 'Contactinformatie',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_phone_label',
                'value_en' => 'Phone',
                'value_pl' => 'Telefon',
                'value_nl' => 'Telefoon',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_phone_available',
                'value_en' => 'Available 24/7',
                'value_pl' => 'Dostępny 24/7',
                'value_nl' => 'Beschikbaar 24/7',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_email_label',
                'value_en' => 'Email',
                'value_pl' => 'E-mail',
                'value_nl' => 'E-mail',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_address_label',
                'value_en' => 'Office Address',
                'value_pl' => 'Adres biura',
                'value_nl' => 'Kantooradres',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_address_line1',
                'value_en' => 'Sunrise & Sunset Home Care',
                'value_pl' => 'Sunrise & Sunset Home Care',
                'value_nl' => 'Sunrise & Sunset Home Care',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_address_line2',
                'value_en' => 'London, United Kingdom',
                'value_pl' => 'Londyn, Wielka Brytania',
                'value_nl' => 'Londen, Verenigd Koninkrijk',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_hours_title',
                'value_en' => 'Opening Hours',
                'value_pl' => 'Godziny otwarcia',
                'value_nl' => 'Openingstijden',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_hours_emergency',
                'value_en' => 'Emergency Support:',
                'value_pl' => 'Wsparcie awaryjne:',
                'value_nl' => 'Noodondersteuning:',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_hours_emergency_time',
                'value_en' => '24/7',
                'value_pl' => '24/7',
                'value_nl' => '24/7',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_hours_office',
                'value_en' => 'Office Hours:',
                'value_pl' => 'Godziny biura:',
                'value_nl' => 'Kantooruren:',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_hours_office_time',
                'value_en' => 'Mon-Fri 9am-6pm',
                'value_pl' => 'Pn-Pt 9:00-18:00',
                'value_nl' => 'Ma-Vr 9u-18u',
                'type' => 'text',
                'group' => 'contact_info',
            ],
            [
                'key' => 'contact_form_title',
                'value_en' => 'Send Us a Message',
                'value_pl' => 'Wyślij nam wiadomość',
                'value_nl' => 'Stuur ons een bericht',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_inquiry_label',
                'value_en' => 'I\'m inquiring about *',
                'value_pl' => 'Pytam o *',
                'value_nl' => 'Ik informeer naar *',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_inquiry_select',
                'value_en' => 'Please select...',
                'value_pl' => 'Proszę wybrać...',
                'value_nl' => 'Selecteer alstublieft...',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_inquiry_myself',
                'value_en' => 'Care for myself',
                'value_pl' => 'Opieka dla mnie',
                'value_nl' => 'Zorg voor mezelf',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_inquiry_loved',
                'value_en' => 'Care for a loved one',
                'value_pl' => 'Opieka dla bliskiej osoby',
                'value_nl' => 'Zorg voor een dierbare',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_inquiry_professional',
                'value_en' => 'Professional referral',
                'value_pl' => 'Skierowanie zawodowe',
                'value_nl' => 'Professionele verwijzing',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_inquiry_job',
                'value_en' => 'Care job opportunities',
                'value_pl' => 'Możliwości pracy w opiece',
                'value_nl' => 'Zorgvacatures',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_inquiry_other',
                'value_en' => 'Other inquiry',
                'value_pl' => 'Inne zapytanie',
                'value_nl' => 'Andere vraag',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_name_label',
                'value_en' => 'Full Name *',
                'value_pl' => 'Pełne imię i nazwisko *',
                'value_nl' => 'Volledige naam *',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_name_placeholder',
                'value_en' => 'Your full name',
                'value_pl' => 'Twoje pełne imię i nazwisko',
                'value_nl' => 'Uw volledige naam',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_email_label',
                'value_en' => 'Email Address *',
                'value_pl' => 'Adres e-mail *',
                'value_nl' => 'E-mailadres *',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_email_placeholder',
                'value_en' => 'your@email.com',
                'value_pl' => 'twoj@email.com',
                'value_nl' => 'uw@email.com',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_phone_label',
                'value_en' => 'Phone Number *',
                'value_pl' => 'Numer telefonu *',
                'value_nl' => 'Telefoonnummer *',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_phone_placeholder',
                'value_en' => '+44 20 xxxx xxxx',
                'value_pl' => '+48 xxx xxx xxx',
                'value_nl' => '+31 xxx xxx xxx',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_time_label',
                'value_en' => 'Preferred Contact Time',
                'value_pl' => 'Preferowany czas kontaktu',
                'value_nl' => 'Voorkeurstijd voor contact',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_time_anytime',
                'value_en' => 'Any time',
                'value_pl' => 'Każdy czas',
                'value_nl' => 'Elke tijd',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_message_label',
                'value_en' => 'Your Message',
                'value_pl' => 'Twoja wiadomość',
                'value_nl' => 'Uw bericht',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_message_placeholder',
                'value_en' => 'Tell us more about your care needs or inquiry...',
                'value_pl' => 'Powiedz nam więcej o swoich potrzebach opiekuńczych lub zapytaniu...',
                'value_nl' => 'Vertel ons meer over uw zorgbehoeften of vraag...',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_submit',
                'value_en' => 'Send Message',
                'value_pl' => 'Wyślij wiadomość',
                'value_nl' => 'Bericht verzenden',
                'type' => 'text',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_form_privacy',
                'value_en' => 'By submitting this form, you consent to us processing your data in accordance with our Privacy Policy.',
                'value_pl' => 'Przesyłając ten formularz, wyrażasz zgodę na przetwarzanie przez nas Twoich danych zgodnie z naszą Polityką prywatności.',
                'value_nl' => 'Door dit formulier in te dienen, stemt u ermee in dat wij uw gegevens verwerken in overeenstemming met ons privacybeleid.',
                'type' => 'textarea',
                'group' => 'contact_form',
            ],
            [
                'key' => 'contact_cta_title',
                'value_en' => 'Prefer to Speak Directly?',
                'value_pl' => 'Wolisz rozmawiać bezpośrednio?',
                'value_nl' => 'Liever direct spreken?',
                'type' => 'text',
                'group' => 'contact_cta',
            ],
            [
                'key' => 'contact_cta_subtitle',
                'value_en' => 'Our friendly team is available 24 hours a day to answer your questions',
                'value_pl' => 'Nasz przyjazny zespół jest dostępny 24 godziny na dobę, aby odpowiedzieć na Twoje pytania',
                'value_nl' => 'Ons vriendelijke team is 24 uur per dag beschikbaar om uw vragen te beantwoorden',
                'type' => 'text',
                'group' => 'contact_cta',
            ],

            // ========================================
            // JOB APPLICATION PAGE
            // ========================================
            [
                'key' => 'jobapp_title',
                'value_en' => 'Apply for Live-In Care Position',
                'value_pl' => 'Aplikuj na stanowisko opiekuna domowego',
                'value_nl' => 'Solliciteer voor thuiszorgpositie',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_subtitle',
                'value_en' => 'Fill out the form below to start your journey with us. All fields marked with * are required.',
                'value_pl' => 'Wypełnij poniższy formularz, aby rozpocząć swoją podróż z nami. Wszystkie pola oznaczone * są wymagane.',
                'value_nl' => 'Vul het onderstaande formulier in om uw reis met ons te beginnen. Alle velden gemarkeerd met * zijn verplicht.',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_personal_title',
                'value_en' => 'Personal Information',
                'value_pl' => 'Informacje osobiste',
                'value_nl' => 'Persoonlijke informatie',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_professional_title',
                'value_en' => 'Professional Information',
                'value_pl' => 'Informacje zawodowe',
                'value_nl' => 'Professionele informatie',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_experience_label',
                'value_en' => 'Previous Care Experience *',
                'value_pl' => 'Poprzednie doświadczenie w opiece *',
                'value_nl' => 'Eerdere zorgervaring *',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_experience_placeholder',
                'value_en' => 'Please describe your previous experience in care work, including roles, responsibilities, and duration...',
                'value_pl' => 'Opisz swoje poprzednie doświadczenie w pracy opiekuńczej, w tym role, obowiązki i czas trwania...',
                'value_nl' => 'Beschrijf uw eerdere ervaring in zorgwerk, inclusief rollen, verantwoordelijkheden en duur...',
                'type' => 'textarea',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_qualifications_label',
                'value_en' => 'Qualifications & Certifications *',
                'value_pl' => 'Kwalifikacje i certyfikaty *',
                'value_nl' => 'Kwalificaties & certificaten *',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_qualifications_placeholder',
                'value_en' => 'Please list your relevant qualifications, certifications, and training (e.g., NVQ, First Aid, etc.)...',
                'value_pl' => 'Wymień swoje odpowiednie kwalifikacje, certyfikaty i szkolenia (np. NVQ, Pierwsza Pomoc itp.)...',
                'value_nl' => 'Vermeld uw relevante kwalificaties, certificaten en trainingen (bijv. NVQ, EHBO, enz.)...',
                'type' => 'textarea',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_additional_title',
                'value_en' => 'Additional Information',
                'value_pl' => 'Dodatkowe informacje',
                'value_nl' => 'Aanvullende informatie',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_right_to_work',
                'value_en' => 'I have the right to work in the UK *',
                'value_pl' => 'Mam prawo do pracy w Wielkiej Brytanii *',
                'value_nl' => 'Ik heb het recht om in het VK te werken *',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_right_to_work_desc',
                'value_en' => 'You must have valid work authorization to apply for this position.',
                'value_pl' => 'Musisz mieć ważne zezwolenie na pracę, aby aplikować na to stanowisko.',
                'value_nl' => 'U moet geldige werkvergunning hebben om voor deze functie te solliciteren.',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_driving_license',
                'value_en' => 'I have a valid driving license',
                'value_pl' => 'Mam ważne prawo jazdy',
                'value_nl' => 'Ik heb een geldig rijbewijs',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_driving_license_desc',
                'value_en' => 'A driving license is preferred but not required.',
                'value_pl' => 'Prawo jazdy jest preferowane, ale nie wymagane.',
                'value_nl' => 'Een rijbewijs heeft de voorkeur maar is niet vereist.',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_cv_title',
                'value_en' => 'CV Upload',
                'value_pl' => 'Przesłanie CV',
                'value_nl' => 'CV uploaden',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_cv_label',
                'value_en' => 'Upload Your CV *',
                'value_pl' => 'Prześlij swoje CV *',
                'value_nl' => 'Upload uw CV *',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_cv_upload',
                'value_en' => 'Upload a file',
                'value_pl' => 'Prześlij plik',
                'value_nl' => 'Upload een bestand',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_cv_drag',
                'value_en' => 'or drag and drop',
                'value_pl' => 'lub przeciągnij i upuść',
                'value_nl' => 'of sleep en zet neer',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_cv_types',
                'value_en' => 'PDF, DOC, DOCX up to 10MB',
                'value_pl' => 'PDF, DOC, DOCX do 10MB',
                'value_nl' => 'PDF, DOC, DOCX tot 10MB',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_cv_success',
                'value_en' => 'File uploaded successfully',
                'value_pl' => 'Plik przesłany pomyślnie',
                'value_nl' => 'Bestand succesvol geüpload',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_required',
                'value_en' => '* Required fields',
                'value_pl' => '* Pola wymagane',
                'value_nl' => '* Verplichte velden',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_submit',
                'value_en' => 'Submit Application',
                'value_pl' => 'Wyślij aplikację',
                'value_nl' => 'Sollicitatie indienen',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_submitting',
                'value_en' => 'Submitting...',
                'value_pl' => 'Wysyłanie...',
                'value_nl' => 'Indienen...',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_help_title',
                'value_en' => 'Need Help?',
                'value_pl' => 'Potrzebujesz pomocy?',
                'value_nl' => 'Hulp nodig?',
                'type' => 'text',
                'group' => 'jobapp',
            ],
            [
                'key' => 'jobapp_help_desc',
                'value_en' => 'If you have any questions about the application process or need assistance, please don\'t hesitate to contact us.',
                'value_pl' => 'Jeśli masz jakiekolwiek pytania dotyczące procesu aplikacji lub potrzebujesz pomocy, nie wahaj się z nami skontaktować.',
                'value_nl' => 'Als u vragen heeft over het sollicitatieproces of hulp nodig heeft, aarzel dan niet om contact met ons op te nemen.',
                'type' => 'textarea',
                'group' => 'jobapp',
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('settings')->updateOrInsert(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('All pages content seeded successfully!');
        $this->command->info('Total settings created: ' . count($settings));
    }
}
